# Generated by Django 4.2.30 on 2026-04-15 17:55

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('destination', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('departure_time', models.DateTimeField()),
                ('available_seats', models.PositiveIntegerField(default=1)),
                ('price_per_seat', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_days', models.CharField(blank=True, help_text='Comma-separated days: mon,tue,wed,thu,fri,sat,sun', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_rides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-departure_time'],
            },
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('dropoff_location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('desired_time', models.DateTimeField()),
                ('seats_needed', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('matched', 'Matched'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_rides', to=settings.AUTH_USER_MODEL)),
                ('ride_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='rides.rideoffer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
