# Generated by Django 4.2.30 on 2026-04-16 13:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_alter_riderequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
