# Generated by Django 4.2.30 on 2026-04-21 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0007_classschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='building',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('bancroft_campus', 'Bancroft (Main) Campus'), ('student_union', 'Thompson Student Union'), ('memorial_field_house', 'Memorial Field House'), ('university_hall', 'University Hall'), ('mulford_library', 'Mulford Health Sciences Library'), ('carlson_library', 'Carlson Library'), ('rocket_hall', 'Rocket Hall'), ('engineering_nitschke', 'Nitschke Hall (Engineering)'), ('engineering_palmer', 'Palmer Hall'), ('engineering_north', 'North Engineering'), ('stranahan_hall', 'Stranahan Hall (Business)'), ('health_education_building', 'Health Education Building'), ('savage_arena', 'Savage Arena'), ('glass_bowl', 'Glass Bowl Stadium'), ('wolfe_hall', 'Wolfe Hall'), ('bowman_oddy', 'Bowman-Oddy Labs'), ('mcmaster_hall', 'McMaster Hall'), ('scott_park_campus', 'Scott Park Campus'), ('health_science_campus', 'Health Science Campus'), ('off_campus', 'Off-Campus / Other')], default='', help_text='Canonical UToledo building — used by the proactive matcher.', max_length=40),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='dispatch_source',
            field=models.CharField(choices=[('manual', 'Manual request'), ('schedule', 'Proactive schedule match')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='dropoff_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='eligible_driver_ids',
            field=models.JSONField(blank=True, default=list, help_text='User IDs of drivers whose current location is within a 5-minute pickup window of the rider. Populated at request creation time; drivers are removed from this list as they reject.'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickup_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickup_eta_seconds',
            field=models.JSONField(blank=True, default=dict, help_text='Map of driver_id -> driver→pickup travel time in seconds (at dispatch time).'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='rejected_driver_ids',
            field=models.JSONField(blank=True, default=list, help_text='User IDs of drivers who explicitly declined this request.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_ride_request',
            field=models.BooleanField(default=True, help_text='When enabled, drivers may be alerted via the in-app dispatch modal whenever a rider within a 5-minute pickup radius submits a request.'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('matched', 'Matched'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_drivers_available', 'No drivers available'), ('pending_rider_confirm', 'Proactive offer — waiting for rider')], default='pending', max_length=24),
        ),
        migrations.CreateModel(
            name='ProactiveRideMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(choices=[('', 'Unspecified'), ('bancroft_campus', 'Bancroft (Main) Campus'), ('student_union', 'Thompson Student Union'), ('memorial_field_house', 'Memorial Field House'), ('university_hall', 'University Hall'), ('mulford_library', 'Mulford Health Sciences Library'), ('carlson_library', 'Carlson Library'), ('rocket_hall', 'Rocket Hall'), ('engineering_nitschke', 'Nitschke Hall (Engineering)'), ('engineering_palmer', 'Palmer Hall'), ('engineering_north', 'North Engineering'), ('stranahan_hall', 'Stranahan Hall (Business)'), ('health_education_building', 'Health Education Building'), ('savage_arena', 'Savage Arena'), ('glass_bowl', 'Glass Bowl Stadium'), ('wolfe_hall', 'Wolfe Hall'), ('bowman_oddy', 'Bowman-Oddy Labs'), ('mcmaster_hall', 'McMaster Hall'), ('scott_park_campus', 'Scott Park Campus'), ('health_science_campus', 'Health Science Campus'), ('off_campus', 'Off-Campus / Other')], default='', max_length=40)),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday')], max_length=3)),
                ('status', models.CharField(choices=[('open', 'Open'), ('offered', 'Offered to rider'), ('declined', 'Declined by driver'), ('expired', 'Expired')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proactive_matches_as_driver', to=settings.AUTH_USER_MODEL)),
                ('driver_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proactive_matches_as_driver', to='rides.classschedule')),
                ('ride_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proactive_matches', to='rides.riderequest')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proactive_matches_as_rider', to=settings.AUTH_USER_MODEL)),
                ('rider_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proactive_matches_as_rider', to='rides.classschedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='proactiveridematch',
            constraint=models.UniqueConstraint(fields=('driver_schedule', 'rider_schedule'), name='unique_proactive_match_per_schedule_pair'),
        ),
    ]
