# Generated by Django 4.2.30 on 2026-04-15 17:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], db_index=True, default='pending', help_text='Current lifecycle stage of the ride.', max_length=12)),
                ('actual_route', django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, help_text='Geographic path of the ride.', null=True, srid=4326)),
                ('total_detour_time', models.IntegerField(default=0, help_text='Total detour time in seconds caused by picking up / dropping off riders.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride_offer', models.ForeignKey(help_text="The driver's ride offer this ride is based on.", on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='rides.rideoffer')),
                ('ride_requests', models.ManyToManyField(blank=True, help_text='Rider requests assigned to this ride.', related_name='rides', to='rides.riderequest')),
            ],
            options={
                'verbose_name': 'Ride',
                'verbose_name_plural': 'Rides',
                'db_table': 'matching_ride',
                'ordering': ['-created_at'],
            },
        ),
    ]
