# Generated by Django 4.2.30 on 2026-04-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('badge_icon', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('achievement_type', models.CharField(choices=[('MILESTONE', 'Milestone'), ('STREAK', 'Streak'), ('SPECIAL', 'Special')], default='MILESTONE', max_length=20)),
                ('required_value', models.IntegerField(help_text='Value required to unlock (e.g., 10 rides)')),
                ('criteria_type', models.CharField(help_text='e.g., rides_given, total_points', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarpoolGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('rank', models.CharField(blank=True, max_length=50)),
                ('frequency', models.IntegerField(default=0)),
                ('last_ride_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('RIDE_GIVEN', 'Ride Given'), ('RIDE_TAKEN', 'Ride Taken'), ('STREAK_BONUS', 'Streak Bonus'), ('MINI_GAME', 'Mini Game Bonus'), ('REDEMPTION', 'Point Redemption')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('max_streak', models.IntegerField(default=0)),
                ('rides_given', models.IntegerField(default=0)),
                ('rides_taken', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'User Stats',
            },
        ),
    ]
