# Generated by Django 4.2.30 on 2026-04-16 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpoolgroup',
            old_name='users',
            new_name='members',
        ),
        migrations.RenameField(
            model_name='carpoolgroup',
            old_name='frequency',
            new_name='ridesCompleted',
        ),
    ]
