# Generated by Django 4.2.30 on 2026-04-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_rename_users_carpoolgroup_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpoolgroup',
            old_name='ridesCompleted',
            new_name='rides_completed',
        ),
    ]
